# File: .github/workflows/refresh.yml
name: Refresh

on:
  schedule:
    - cron:  '*/5 * * * *' # Run every 5 minutes

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/agenovia/agenovia.github.io/pages/builds
