# File: .github/workflows/request_build.yml
name: Refresh

on:
  schedule:
    - cron:  '37 * * * *' # Runs every 33rd minute

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/agenovia/agenovia.github.io/pages/builds
