name: rebuild pages every hour

on:
  schedule:
    - cron:  '*/30 * * * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        env:
          token: ${{ secrets.USER_TOKEN }}
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $token" \
          https://api.github.com/repos/agenovia/agenovia.github.io/pages/builds
